listings_columns = ['id','number_of_reviews', 'latitude', 'longitude', 'amenities',
                    'security_deposit', 'cleaning_fee', 'neighbourhood_cleansed', 'bed_type', 'experiences_offered',
                    'host_verifications', 'review_scores_location', 'cancellation_policy', 'price', 'room_type',
                    'reviews_per_month', 'accommodates', 'review_scores_rating', 'host_is_superhost',
                    'host_listings_count', 'availability_30']#'first_review', 'last_review',
